# -*- coding: utf-8 -*-
# Part of Softhealer Technologies.
{
    "name": "Backmate Backend Theme Advance",
    "author": "Softhealer Technologies",
    "website": "https://www.softhealer.com",
    "support": "support@softhealer.com",
    "description": """
                Are you bored with your standard odoo backend theme? Are You are looking for modern, creative, clean, clear, materialize Odoo theme for your backend? So you are at right place, We have made sure that this theme is highly customizable and it comes with a premium look and feel. Our theme is not only beautifully designed but also fully functional, flexible, fast, lightweight, animated and modern multipurpose theme. Our backend theme is suitable for almost every purpose.
                """,
    "summary": "Advance Material Backend Theme, Responsive Theme, Fully functional Theme, flexible Backend Theme, fast Backend Theme, lightweight Backend Theme, Animated Backend Theme, Modern multipurpose theme, Customizable Backend Theme, Multi Tab Backend Theme Odoo",
    "category": "Theme/Backend",
    "version": "15.0.3",
    "depends":
    [
        "web", "mail"
    ],

    "data":
    [
        "security/base_security.xml",
        "security/ir.model.access.csv",
        "data/theme_config_data.xml",
        "data/pwa_configuraion_data.xml",
        # "views/assets.xml",
        "views/login_layout.xml",
        "views/back_theme_config_view.xml",
        "views/assets_backend.xml",
        #          "wizard/theme_preview_wizard.xml",
        "views/res_config_settings.xml",
        "views/base_view.xml",
        "views/global_search_view.xml",
        "views/pwa_configuration_view.xml",
        "views/views.xml",
        "views/notifications_view.xml",
        "views/send_notifications.xml",
        "views/web_push_notification.xml",
        
    ],
     'assets': {
       
        'web.assets_backend': [
            "sh_backmate_theme_adv/static/src/scss/font/fonts.scss",
            "sh_backmate_theme_adv/static/src/scss/style.css",
            "sh_backmate_theme_adv/static/src/scss/quick_menu/quick_menu.scss",
            "sh_backmate_theme_adv/static/src/js/quick_menu.js",
            "sh_backmate_theme_adv/static/src/scss/global_search/global_search.scss",
            "sh_backmate_theme_adv/static/src/js/global_search.js",
            "sh_backmate_theme_adv/static/src/js/vertical_pen.js",
            "sh_backmate_theme_adv/static/src/js/message_toggle.js",
            "sh_backmate_theme_adv/static/src/js/calculator.js",
            "sh_backmate_theme_adv/static/src/scss/night.scss",
             "sh_backmate_theme_adv/static/src/scss/night_mode_user.scss",
            "sh_backmate_theme_adv/static/src/scss/switch_button.scss",
            "sh_backmate_theme_adv/static/src/scss/theme_config.scss",
            "sh_backmate_theme_adv/static/src/js/theme_config.js",
            "sh_backmate_theme_adv/static/src/js/theme_configuration_widget.js",
            "sh_backmate_theme_adv/static/src/js/module_icon.js",
            "sh_backmate_theme_adv/static/src/scss/theme.scss",
            "sh_backmate_theme_adv/static/src/scss/font/font.scss",
            "sh_backmate_theme_adv/static/src/scss/button/buttons.scss",
            "sh_backmate_theme_adv/static/src/scss/background/body_background_img/background-img.scss",
            "sh_backmate_theme_adv/static/src/scss/sidebar/sidebar_style_1.scss",
            "sh_backmate_theme_adv/static/src/scss/sidebar/sidebar_style_2.scss",
            "sh_backmate_theme_adv/static/src/scss/sidebar/sidebar_style_3.scss",
            "sh_backmate_theme_adv/static/src/scss/sidebar/expaned.scss",
            "sh_backmate_theme_adv/static/src/scss/sidebar/collapsed.scss",
            "sh_backmate_theme_adv/static/src/scss/sidebar/sidebar_bg.scss",
            "sh_backmate_theme_adv/static/src/scss/breadcrumb/breadcrumb.scss",
            "sh_backmate_theme_adv/static/src/scss/separator/separator.scss",
            "sh_backmate_theme_adv/static/src/scss/navbar/navbar.scss",
            "sh_backmate_theme_adv/static/src/scss/form_view/form_view.scss",
            "sh_backmate_theme_adv/static/src/scss/button/button_icon.scss",
            "sh_backmate_theme_adv/static/src/scss/theme_style_4.scss",
            # "sh_backmate_theme_adv/static/src/scss/popup/popup_style.scss",
            "sh_backmate_theme_adv/static/src/scss/responsive/responsive_theme.scss",
            "sh_backmate_theme_adv/static/src/scss/tab/tab.scss",
            "sh_backmate_theme_adv/static/src/scss/form_element_style/form_element_style.scss",
            "sh_backmate_theme_adv/static/src/scss/calculator/calculator.scss",
            "sh_backmate_theme_adv/static/src/scss/notification/notification.scss",
            "sh_backmate_theme_adv/static/src/scss/chatter_position/chatter_position.scss",
            # "sh_backmate_theme_adv/static/src/js/sh_bus_notification.js",
            # "sh_backmate_theme_adv/static/src/js/web_notification.js",
            "sh_backmate_theme_adv/static/src/scss/loader/loader.scss",
            "sh_backmate_theme_adv/static/src/scss/nprogress/nprogress.scss",
            "sh_backmate_theme_adv/static/src/js/nprogress.js",
            "sh_backmate_theme_adv/static/src/js/progressbar.js",
            "sh_backmate_theme_adv/static/src/scss/predefine_style_1/body_style.scss",
            "sh_backmate_theme_adv/static/src/scss/predefine_style_1/navbar_style.scss",
            "sh_backmate_theme_adv/static/src/scss/predefine_style_1/control_panel_style.scss",
            # "sh_backmate_theme_adv/static/src/js/customize_user.js",
            "sh_backmate_theme_adv/static/src/js/night_mode.js",
            "sh_backmate_theme_adv/static/src/scss/sticky/sticky_chatter.scss",
            "sh_backmate_theme_adv/static/src/scss/sticky/sticky_form.scss",
            "sh_backmate_theme_adv/static/src/scss/sticky/sticky_list_inside_form.scss",
            "sh_backmate_theme_adv/static/src/scss/sticky/sticky_list.scss",
            "sh_backmate_theme_adv/static/src/js/menu.js",
            "sh_backmate_theme_adv/static/src/js/status_bar.js",
            "sh_backmate_theme_adv/static/src/js/control_panel.js",
            "sh_backmate_theme_adv/static/src/scss/background/body_background_color/background-color.scss",
            "sh_backmate_theme_adv/static/src/js/apps_menu.js",
            "sh_backmate_theme_adv/static/src/js/user_menu.js",
            ('replace', 'web/static/src/webclient/user_menu/user_menu.js', 'sh_backmate_theme_adv/static/src/js/systray_user_menu.js'),        

            "sh_backmate_theme_adv/static/index.js",
            "https://www.gstatic.com/firebasejs/8.4.3/firebase-app.js",
            "https://www.gstatic.com/firebasejs/8.4.3/firebase-messaging.js",
            "sh_backmate_theme_adv/static/src/js/firebase.js",
            "sh_backmate_theme_adv/static/src/js/navbar.js",
           'sh_backmate_theme_adv/static/src/js/action_container.js',
            'sh_backmate_theme_adv/static/src/js/dropdown.js',
            'sh_backmate_theme_adv/static/src/js/custom.js',
            'sh_backmate_theme_adv/static/src/js/bus_notification.js',
        ],
          'web.assets_frontend': [       
            'sh_backmate_theme_adv/static/src/scss/login_page/login_style.css',
            'sh_backmate_theme_adv/static/src/scss/login_page/login_style_1.scss',
            'sh_backmate_theme_adv/static/src/scss/login_page/login_style_2.scss',
            'sh_backmate_theme_adv/static/src/scss/login_page/login_style_3.scss',
            'sh_backmate_theme_adv/static/src/scss/login_page/login_style_4.scss'
           
        ],
         'web._assets_primary_variables': [
          ('after', 'web/static/src/legacy/scss/primary_variables.scss', '/sh_backmate_theme_adv/static/src/scss/back_theme_config_main_scss.scss'),        
        ],
        'web.assets_qweb': [
                "sh_backmate_theme_adv/static/src/xml/web_quick_menu.xml",
                "sh_backmate_theme_adv/static/src/xml/global_search.xml",
                "sh_backmate_theme_adv/static/src/xml/sh_thread.xml",
                "sh_backmate_theme_adv/static/src/xml/menu.xml",
                "sh_backmate_theme_adv/static/src/xml/navbar.xml",
                "sh_backmate_theme_adv/static/src/xml/form_view.xml",
                "sh_backmate_theme_adv/static/src/xml/theme_config.xml",
                "sh_backmate_theme_adv/static/src/xml/base.xml",
        ],
        
      
       
    },
 
    'images': [
        'static/description/splash-screen.png',
        'static/description/splash-screen_screenshot.gif'
    ],
    "live_test_url": "https://softhealer.com/contact_us",
    "installable": True,
    "application": True,
    "price": 125,
    "currency": "EUR",
    "bootstrap": True,
    "license": "OPL-1",

}
