# -*- coding: utf-8 -*-
{
    'name': "Hr Loans",
    'summary': ' Hr Loans',
    'description': " Hr Loans ",
    'author': "OserGroup",
    'website': "http://www.osergroup.com",
    'category': 'Hr',
    'version': '0.1',
    'depends': [
        'mail',
        'base',
        'hr',
        'ext_hr_employee',
        'ext_hr_contract',
        'ext_hr_payroll',
        'mits_hr_leaves',
        'account',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/data.xml',
        'data/mail_template.xml',
        'views/views.xml',
        'views/skip_installment_view.xml',
        # 'views/hr_loans.xml',
        'views/hr_rewards.xml',
        'views/request_sequence.xml',
        'views/salary_structure_data.xml',
        # 'views/res_config_view.xml',
        'views/configuration.xml',
        'views/skip_installment_mail_template.xml',
        'views/hr_employee_view.xml',
        'views/loan_salary_advance_view.xml',
        'report/loan_report.xml',
        'wizard/loan_payment_view.xml',
        'wizard/loan_report_view.xml',
    ],
}